### PR TITLE
feature adding more than one secret

### PR DESCRIPTION
**Pull request by ismferd**
Hi,

Thanks for your module, I need add more than one secret at time.

So, I did this PR just to do it trying not do breaking changes. 
please take a look!

Thanks.

### CODE REVIEW

**Comment by sblack4** [comment]
Thank you! It looks like you added the ability to store a json file (passed in as a map) as the secret value. Is that what you were intending or did you want to create multiple different secrets?

**Comment by ismferd** [comment]
yeah, that's it. store a map of secrets.

**Comment by sblack4** [comment]
I have an easier solution 😄 ! When you call the module pass in your json-encoded map to the value attribute, like in this example. It fixes the problem by converting the map to a string before calling the module

```hcl
variable "secrets" {
  description = "User-Defined secrets"
  type        = map(string)
  default     = {}
}

module "secret" {
  source  = "rhythmictech/secretsmanager-secret/aws"
  version = "0.1.0"
  
  name  = "my-json-secrets"
  value = jsonencode(var.secrets)

  tags = {
      encoding = "base64"
      type     = "json"
  }
}
```

**Comment by ismferd** [comment]
ok! 
Thanks for your tip @sblack4 , I'm closing the PR.

**Comment by sblack4** [comment]
NP 🥳

**Pull request closed without merging**
